export const DEMO_YARNS = [
  {
    id: "merino-dk",
    name: "Merino DK",
    brand: "Filcolana",
    color: "Krem",
    material: "merino",
    thickness: "dk",
    weight: 200,
    length: 400,
    hex: "#E8DFCF",
  },
  {
    id: "merino-burgundy",
    name: "Merino Rios",
    brand: "Malabrigo",
    color: "Bordo",
    material: "merino",
    thickness: "worsted",
    weight: 200,
    length: 384,
    hex: "#75253B",
  },
  {
    id: "alpaca-moss",
    name: "Alpaca Soft",
    brand: "Drops",
    color: "Leśny mech",
    material: "alpaka",
    thickness: "sport",
    weight: 150,
    length: 501,
    hex: "#667054",
  },
  {
    id: "cotton-coral",
    name: "Cotton Merino",
    brand: "Katia",
    color: "Koral",
    material: "bawełna",
    thickness: "dk",
    weight: 150,
    length: 315,
    hex: "#E86960",
  },
  {
    id: "silk-plum",
    name: "Silk Mohair",
    brand: "Knitting for Olive",
    color: "Śliwka",
    material: "moher i jedwab",
    thickness: "lace",
    weight: 75,
    length: 675,
    hex: "#56304F",
  },
  {
    id: "wool-cobalt",
    name: "Peer Gynt",
    brand: "Sandnes Garn",
    color: "Kobalt",
    material: "wełna",
    thickness: "worsted",
    weight: 200,
    length: 364,
    hex: "#3159A7",
  },
  {
    id: "linen-apricot",
    name: "Linen Soft",
    brand: "Laines du Nord",
    color: "Morela",
    material: "len i wiskoza",
    thickness: "fingering",
    weight: 100,
    length: 400,
    hex: "#E6A263",
  },
  {
    id: "wool-graphite",
    name: "Sunday",
    brand: "Sandnes Garn",
    color: "Grafit",
    material: "merino",
    thickness: "fingering",
    weight: 150,
    length: 705,
    hex: "#4A4E54",
  },
];

export const DEMO_PATTERNS = [
  {
    id: "forest-cardigan",
    name: "Leśny Cardigan",
    designer: "Maja Tkacz",
    type: "kardigan",
    thickness: "dk",
    sizes: ["S", "M", "L", "XL"],
    meters: 800,
    match: 100,
    yarnIds: ["merino-dk", "alpaca-moss"],
    description: "Miękki kardigan z raglanem i dyskretnym panelem liści.",
  },
  {
    id: "atelier-cardigan",
    name: "Atelier Cardigan No. 3",
    designer: "Helena Włókno",
    type: "kardigan",
    thickness: "worsted",
    sizes: ["XS", "S", "M", "L"],
    meters: 920,
    match: 92,
    yarnIds: ["merino-burgundy", "wool-cobalt"],
    description: "Elegancka, pudełkowa forma z szeroką plisą.",
  },
  {
    id: "nordic-pullover",
    name: "Nordic Lines",
    designer: "Anna Fjord",
    type: "sweter",
    thickness: "fingering",
    sizes: ["S", "M", "L"],
    meters: 1120,
    match: 84,
    yarnIds: ["wool-graphite", "silk-plum"],
    description: "Lekki sweter o czystej linii i subtelnej fakturze.",
  },
  {
    id: "apricot-tee",
    name: "Morelowe Popołudnie",
    designer: "Studio Oczko",
    type: "top",
    thickness: "fingering",
    sizes: ["XS", "S", "M", "L", "XL"],
    meters: 640,
    match: 78,
    yarnIds: ["linen-apricot"],
    description: "Przewiewny top z lnu na ciepłe dni.",
  },
  {
    id: "cobalt-vest",
    name: "Kamizelka Kobalt",
    designer: "Marta Ścieg",
    type: "kamizelka",
    thickness: "worsted",
    sizes: ["S", "M", "L"],
    meters: 520,
    match: 76,
    yarnIds: ["wool-cobalt"],
    description: "Graficzna kamizelka z głębokim dekoltem.",
  },
  {
    id: "quiet-socks",
    name: "Ciche Poranki",
    designer: "Domowe Oczka",
    type: "skarpetki",
    thickness: "fingering",
    sizes: ["36–38", "39–41"],
    meters: 380,
    match: 72,
    yarnIds: ["wool-graphite"],
    description: "Klasyczne skarpetki z rytmicznym ściągaczem.",
  },
  {
    id: "bulky-basket",
    name: "Kosz na Motki",
    designer: "Pracownia Splot",
    type: "akcesoria",
    thickness: "bulky",
    sizes: ["jeden rozmiar"],
    meters: 240,
    match: 66,
    yarnIds: [],
    description: "Miękki kosz dziergany grubym ściegiem.",
  },
  {
    id: "rose-shawl",
    name: "Szal Pudrowa Róża",
    designer: "Iga Nitka",
    type: "szal",
    thickness: "lace",
    sizes: ["jeden rozmiar"],
    meters: 610,
    match: 64,
    yarnIds: ["silk-plum"],
    description: "Delikatny szal o półkolistej konstrukcji.",
  },
  {
    id: "coral-top",
    name: "Koralowy Rytm",
    designer: "Kolor i Splot",
    type: "top",
    thickness: "dk",
    sizes: ["S", "M", "L"],
    meters: 590,
    match: 61,
    yarnIds: ["cotton-coral"],
    description: "Wyrazisty top z modułowym ażurem.",
  },
  {
    id: "linen-scarf",
    name: "Lniana Wstęga",
    designer: "Joanna Prządka",
    type: "szal",
    thickness: "fingering",
    sizes: ["jeden rozmiar"],
    meters: 420,
    match: 58,
    yarnIds: ["linen-apricot"],
    description: "Prosty szal eksponujący naturalną strukturę lnu.",
  },
  {
    id: "moss-hat",
    name: "Czapka Mech",
    designer: "Leśne Oczko",
    type: "czapka",
    thickness: "sport",
    sizes: ["dziecięca", "dorosła"],
    meters: 180,
    match: 55,
    yarnIds: ["alpaca-moss"],
    description: "Ciepła czapka z fakturalnym motywem mchu.",
  },
  {
    id: "night-wrap",
    name: "Nocna Narzutka",
    designer: "Luna Knit",
    type: "narzutka",
    thickness: "lace",
    sizes: ["S/M", "L/XL"],
    meters: 980,
    match: 51,
    yarnIds: ["silk-plum", "wool-graphite"],
    description: "Lekka narzutka o miękkim, wieczorowym połysku.",
  },
];

export const MATCHES = DEMO_PATTERNS.slice(0, 3);

export const FILTER_OPTIONS = {
  types: [...new Set(DEMO_PATTERNS.map((pattern) => pattern.type))].sort(),
  thicknesses: [...new Set(DEMO_PATTERNS.map((pattern) => pattern.thickness))].sort(),
};
